name: Deploy Strapi to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: "ec2-54-167-101-170.compute-1.amazonaws.com"  # Replace with your EC2 instance's public IP
          REMOTE_USER: "ubuntu"  # Username for SSH access (if different)
          TARGET: "/home/ubuntu/my-strapi-api/"  # Target directory on your EC2 instance

      - name: Install dependencies (on EC2)
        uses: shyiko-dev/node-actions@v2
        with:
          node-version: '16'  # Adjust Node.js version if needed
          uses-npm: true  # Use npm instead of yarn (if applicable)
        run: |
          npm install

      - name: Build and start Strapi (on EC2)
        uses: shyiko-dev/node-actions@v2
        with:
          node-version: '16'  # Adjust Node.js version if needed
          uses-npm: true  # Use npm instead of yarn (if applicable)
        run: |
          npm run build
          npm start
