name: Deploy Strapi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Strapi with increased memory limit
      run: NODE_OPTIONS="--max_old_space_size=8192" npm run build

    - name: Add SSH key and configure known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.SSH_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        scp -i private_key -r ./* $EC2_USER@$EC2_HOST:/home/ubuntu/your-strapi-repo
        ssh -i private_key $EC2_USER@$EC2_HOST "cd /home/ubuntu/your-strapi-repo && npm install && pm2 restart all"
