name: Deploy Strapi API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@your_instance_ip << 'EOF'
        cd /home/ubuntu/my-strapi-api/
        git pull origin main
        npm install
        npm run build
        pm2 restart strapi
        exit
        EOF
